const dicas = [
    "Comente seu código — até você pode esquecer o que fez.",
    "Evite repetir código: use funções.",
    "Use o console.log como seu melhor amigo para debug.",
    "Aprenda Git. Vai salvar sua vida um dia.",
    "Não copie e cole sem entender.",
    "Faça pausas. Mente cansada não resolve bugs.",
    "Documentação é ouro. Leia ela.",
    "Aprender dev é maratona, não corrida.",
    "Erro? Ótimo, é assim que se aprende.",
    "Organize seus arquivos. Bagunça dá dor de cabeça.",
    "Use nomes claros para variáveis e funções.",
    "Pratique todo dia, nem que seja 20 minutos.",
    "Teste seu código com frequência. O quanto antes, melhor.",
    "Seja curioso! Aprender algo novo todos os dias te torna mais forte.",
    "O Google é seu amigo. Use-o com sabedoria.",
    "Não tenha medo de errar — errar é parte do processo.",
    "Deixe o código simples. O simples é mais eficiente e fácil de entender.",
    "Acredite no processo, mesmo quando não entender algo de imediato.",
    "Estude sobre estruturas de dados e algoritmos. Vai mudar seu jogo.",
    "Aprenda a ler mensagens de erro — elas estão tentando te ajudar.",
    "Coloque seu código no GitHub. Além de aprender, você cria um portfólio.",
    "Sempre que possível, refatore o código. Melhorar é sempre uma boa prática.",
    "Foque em qualidade, não apenas em velocidade.",
    "Leia livros de programação. Eles abrem sua mente para novas perspectivas.",
    "Construa projetos práticos. Colocar a teoria em prática é crucial.",
    "Você não precisa saber tudo. Concentre-se no que é mais importante no momento.",
    "Não se compare com os outros. Cada jornada é única.",
    "Estude código de outras pessoas. Vai te ensinar boas práticas e truques.",
    "Use um editor de código que você goste. A produtividade vai lá em cima.",
    "Mantenha o foco em um problema por vez. Não fique pulando de um para outro.",
    "Sempre que terminar uma tarefa, reveja o que fez. Isso te ajuda a melhorar.",
    "Seja persistente. Às vezes, você só precisa de mais tempo para resolver um problema.",
    "Não tenha vergonha de pedir ajuda. Ninguém sabe tudo.",
    "Aprenda a usar ferramentas como o Postman e o Insomnia para testar APIs.",
    "Entenda o básico de redes e como as aplicações se comunicam.",
    "Se organize. Ferramentas como o Trello podem ser uma mão na roda.",
    "Não trabalhe só com o que é fácil. Enfrente desafios para evoluir.",
    "Evite procrastinação. Faça um pouco por vez, mas faça sempre.",
    "Revise seu código várias vezes antes de finalizar.",
    "Mantenha-se atualizado. O mundo da tecnologia muda rápido.",
    "Trabalhe em equipe. Ninguém cresce sozinho.",
    "Não tenha medo de mudar seu código. Refatoração é sempre bem-vinda.",
    "Estude as melhores práticas de segurança. Hackers estão por aí.",
    "Estabeleça metas claras e pequenos objetivos.",
    "Exercícios de lógica são uma ótima maneira de melhorar suas habilidades.",
    "A linguagem que você usa não é tão importante quanto a lógica que você aplica.",
    "Nunca pare de aprender. A tecnologia nunca para de evoluir.",
    "Ao fazer um código mais complexo, divida-o em pequenas partes.",
    "Entenda a teoria por trás da programação, não só a prática.",
    "Seja paciente. Às vezes o erro mais simples está na coisa mais óbvia.",
    "A programação exige lógica, mas também criatividade.",
    "Programe com propósito. Entenda o porquê de cada linha de código.",
    "Aprenda e domine o uso de frameworks. Eles facilitam muito o trabalho.",
    "Seja disciplinado. Criar hábitos de estudo vai te fazer melhorar rapidamente.",
    "Nunca subestime o poder do feedback. Escute os outros, sempre.",
    "Experimente, errando e aprendendo, você vai dominar.",
    "Aprenda a usar ferramentas de versionamento como Git.",
    "Estude sempre! Todo dia é um passo a mais.",
    "Lembre-se de que todos os desenvolvedores já foram iniciantes um dia.",
    "Não tenha medo de perguntar. É assim que se aprende.",
    "Cada problema resolvido é uma vitória.",
    "Sempre que possível, faça backup de seu trabalho.",
    "A programação é uma habilidade prática. Então, pratique constantemente."
  ];
  
  function mostrarDica() {
    const indice = Math.floor(Math.random() * dicas.length);
    document.getElementById("dica").textContent = dicas[indice];
  }
  